#!/bin/sh

if [ "$1" = "floating" ]; then
	/usr/bin/telegram-desktop
	xdotool search \
		--maxdepth 1 \
		--onlyvisible \
		--class "Telegram" windowsize 380 480 windowmove 1730 840

else
	/usr/bin/telegram-desktop "$@"
fi
