#!/bin/sh

# Idea follows XDG Specs but java doesnt, so it creates "$HOME/.java/fonts/"
# Java uses property "user.home" so wee can change it with "-Duser.home".
# Read more at:
# >  https://github.com/openjdk/jdk/blob/master/src/java.desktop/unix/classes/sun/font/FcFontConfiguration.java
# >  private File getFcInfoFile()

# Prevent ~/.android/*keys*
HOME="$XDG_DATA_HOME/android"

# Prevent ~/.java/fonts
_JAVA_OPTIONS="$_JAVA_OPTIONS -Duser.home=$XDG_DATA_HOME"

/usr/bin/idea "$@"
