#!/bin/sh

export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"

cleanup() {
	rm "$FIFO_UEBERZUG" 2>/dev/null
	pkill -P $$ 2>/dev/null
}

if [ "$(tty)" = "/dev/tty1" ]; then
	/usr/bin/vifm "$@"
else

	rm "$FIFO_UEBERZUG" 2>/dev/null
	mkfifo "$FIFO_UEBERZUG"
	trap cleanup EXIT
	tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser bash &

	/usr/bin/vifm "$@"
	cleanup
fi
