#!/bin/sh

if [ "$(tty)" = "/dev/tty1" ]; then
	/usr/bin/vifm "$@"
else
	export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"
	rm "$FIFO_UEBERZUG" 2>/dev/null
	mkfifo "$FIFO_UEBERZUG"
	trap cleanup EXIT
	tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser bash &
	/usr/bin/vifm "$@"
	rm "$FIFO_UEBERZUG" 2>/dev/null
	pkill -P $$ 2>/dev/null
fi
